
volumes:
    n8n-db:

networks:
    n8n_net:
        driver: bridge

services:
  app:
    image: n8nio/n8n:0.130.0
    container_name: "n8n_app"
    volumes:
      - ./dot-n8n:/home/Desktop/node/.n8n
    environment:
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_DATABASE=${MYSQL_DATABASE}
      - DB_MYSQLDB_HOST=db
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_USER=${MYSQL_USER}
      - DB_MYSQLDB_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - n8n_net
    ports:
      - 5678:5678
    depends_on:
     - db
    restart: unless-stopped
  db:
    image: mysql:5.7
    container_name: "n8n_db"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - n8n-db:/var/lib/mysql
    networks:
      - n8n_net
    ports:
      - 3306:3306
    restart: unless-stopped
